### ISSUE TITLE
don't working on ruby 2.1.0

### ISSUE THREAD

**Issue by aelaa** [gma/tconsole#75]
"An error occured: undefined method `suite_counts' for :run:Symbol
Couldn't load the test environment. Exiting." 
Just on trying to run tconsole.
Ubuntu 12.04, ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]
